title: Jihong Min
description: Academic Profile
show_downloads: false
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
url: "https://hurryman2212.github.io"
baseurl: ""
plugins:
- jekyll-remote-theme